# This is a basic workflow that is manually triggered

name: Build workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'branch name of "https://github.com/Shuanglu/istio"'
        # Default value if no value is explicitly provided
        default: 'master'
        # Input has to be provided for the workflow to run
        required: true
      hub:
        description: 'dockerhub name to push image'
        default: 'shawnlu'
        required: true
      component:
        description: 'component to build. "all" or "<specific component eg. pilot>'
        default: 'all'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: checkout
      uses: actions/checkout@v2.4.2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: execute 'make' for all components
      run: make DEBUG=1 push.docker
      if: ${{ github.event.inputs.component }} == 'all'
    - name: execute 'make' for individual component
      run: make DEBUG=1 push.docker.${{ github.event.inputs.component }} 
      if: ${{ github.event.inputs.component }} != 'all'
